---
-
  hosts: centos
  name: RedHat Zabbix Agent Installing
  tasks:
      - name: "RedHat | Install gpg key"
        rpm_key:
            state: present
            key: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
        become: true


      - name: yum updates
        yum: update_cache=yes

########################################

      - name: "RedHat | Installing Yum Repository"
        become: yes
        yum_repository:
          baseurl: "https://repo.zabbix.com/zabbix/4.4/rhel/{{ ansible_distribution_major_version }}/$basearch/"
          gpgcheck: true
          name: Zabbix
          gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
          description: Zabbix Official Repository - $basearch
  

        
########################################

      - name: "RedHat  | Installing Zabbix-agent"
        become: yes
        yum:
            name: zabbix-agent
            state: present
            update_cache: yes
        notify: zabbix_agent_restart    


########################################
########################################

      - become: true
        name: CONFIGURE zabbix-agent
        copy:
          src: /var/lib/awx/projects/zabbix/redhat_zabbix_agentd.conf
          dest: /etc/zabbix/zabbix_agentd.conf
          owner: root
          group: root
          mode: '0644'
        notify: zabbix_agent_restart 

########################################
########################################

  handlers:

    - become: true
      name: 'zabbix_agent_restart'
      systemd:
          name: zabbix-agent
          state: restarted
          enabled: yes